// <auto-generated />
using CamelliaWiki.Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CamelliaWiki.Backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Articles.Article", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("path");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("ID", "Language");

                    b.ToTable("article");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Articles.ArticleAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("article");

                    b.HasKey("Alias");

                    b.ToTable("alias");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Articles.ArticleMetadata", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<long?>("Date")
                        .HasColumnType("bigint")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("layout");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("ID", "Language");

                    b.ToTable("article-meta");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Characters.Character", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("character", (string)null);
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Comments.Comment", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("AuthorID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("content");

                    b.Property<long>("LastEdited")
                        .HasColumnType("bigint")
                        .HasColumnName("edited");

                    b.Property<string>("ParentID")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent");

                    b.Property<string>("PostSlug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("ParentID");

                    b.ToTable("comment");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Comments.CommentVote", b =>
                {
                    b.Property<string>("CommentID")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("UserID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user");

                    b.Property<bool?>("Value")
                        .HasColumnType("boolean")
                        .HasColumnName("value");

                    b.HasKey("CommentID", "UserID");

                    b.ToTable("comment-vote");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Discography.DiscographyAlbum", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("TitleRomanized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title_romanized");

                    b.HasKey("ID");

                    b.ToTable("album", (string)null);
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Discography.DiscographyTrack", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Albums")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("albums");

                    b.Property<string>("BPM")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bpm");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("length");

                    b.Property<bool>("Single")
                        .HasColumnType("boolean")
                        .HasColumnName("single");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("TitleRomanized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title_romanized");

                    b.HasKey("ID");

                    b.ToTable("track", (string)null);
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.DynamicData", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("integer")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("dynamic");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Users.User", b =>
                {
                    b.Property<decimal>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("avatar");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("banner");

                    b.Property<long>("JoinDate")
                        .HasColumnType("bigint")
                        .HasColumnName("join");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("user");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Articles.ArticleMetadata", b =>
                {
                    b.HasOne("CamelliaWiki.Backend.Models.Articles.Article", "Article")
                        .WithOne("Metadata")
                        .HasForeignKey("CamelliaWiki.Backend.Models.Articles.ArticleMetadata", "ID", "Language")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Characters.Character", b =>
                {
                    b.OwnsMany("CamelliaWiki.Backend.Models.Characters.CharacterImage", "Images", b1 =>
                        {
                            b1.Property<string>("character")
                                .HasColumnType("character varying(128)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AltText")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("alt");

                            b1.Property<string>("ImageSource")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("src");

                            b1.HasKey("character", "Id");

                            b1.ToTable("character-image", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("character");
                        });

                    b.Navigation("Images");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Comments.Comment", b =>
                {
                    b.HasOne("CamelliaWiki.Backend.Models.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamelliaWiki.Backend.Models.Comments.Comment", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentID");

                    b.Navigation("Author");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Comments.CommentVote", b =>
                {
                    b.HasOne("CamelliaWiki.Backend.Models.Comments.Comment", "Comment")
                        .WithMany("Votes")
                        .HasForeignKey("CommentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Discography.DiscographyAlbum", b =>
                {
                    b.OwnsMany("CamelliaWiki.Backend.Models.Discography.DiscographyCover", "Covers", b1 =>
                        {
                            b1.Property<string>("album")
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.HasKey("album", "Id");

                            b1.ToTable("album-cover", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("album");
                        });

                    b.OwnsMany("CamelliaWiki.Backend.Models.Discography.DiscographyCredit", "Credits", b1 =>
                        {
                            b1.Property<string>("album")
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("role");

                            b1.HasKey("album", "Id");

                            b1.ToTable("album-credit", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("album");
                        });

                    b.OwnsMany("CamelliaWiki.Backend.Models.Discography.DiscographyLink", "Links", b1 =>
                        {
                            b1.Property<string>("album")
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("label");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.HasKey("album", "Id");

                            b1.ToTable("album-link", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("album");
                        });

                    b.OwnsOne("CamelliaWiki.Backend.Models.Discography.DiscographyRelease", "Release", b1 =>
                        {
                            b1.Property<string>("album")
                                .HasColumnType("character varying(256)");

                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("day");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("month");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("year");

                            b1.HasKey("album");

                            b1.ToTable("album-release", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("album");
                        });

                    b.OwnsMany("CamelliaWiki.Backend.Models.Discography.DiscographyDisc", "Discs", b1 =>
                        {
                            b1.Property<string>("album")
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.PrimitiveCollection<string[]>("Tracks")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("tracks");

                            b1.HasKey("album", "Id");

                            b1.ToTable("album-disc", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("album");
                        });

                    b.Navigation("Covers");

                    b.Navigation("Credits");

                    b.Navigation("Discs");

                    b.Navigation("Links");

                    b.Navigation("Release")
                        .IsRequired();
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Discography.DiscographyTrack", b =>
                {
                    b.OwnsMany("CamelliaWiki.Backend.Models.Discography.DiscographyCover", "Covers", b1 =>
                        {
                            b1.Property<string>("track")
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.HasKey("track", "Id");

                            b1.ToTable("track-cover", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("track");
                        });

                    b.OwnsMany("CamelliaWiki.Backend.Models.Discography.DiscographyCredit", "Credits", b1 =>
                        {
                            b1.Property<string>("track")
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("role");

                            b1.HasKey("track", "Id");

                            b1.ToTable("track-credit", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("track");
                        });

                    b.OwnsMany("CamelliaWiki.Backend.Models.Discography.DiscographyLink", "Links", b1 =>
                        {
                            b1.Property<string>("track")
                                .HasColumnType("character varying(256)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("label");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.HasKey("track", "Id");

                            b1.ToTable("track-link", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("track");
                        });

                    b.OwnsOne("CamelliaWiki.Backend.Models.Discography.DiscographyRelease", "Release", b1 =>
                        {
                            b1.Property<string>("track")
                                .HasColumnType("character varying(256)");

                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("day");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("month");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("year");

                            b1.HasKey("track");

                            b1.ToTable("track-release", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("track");
                        });

                    b.Navigation("Covers");

                    b.Navigation("Credits");

                    b.Navigation("Links");

                    b.Navigation("Release")
                        .IsRequired();
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Articles.Article", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("CamelliaWiki.Backend.Models.Comments.Comment", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
